#!/bin/sh

# Requêtes pour mettre à jour certaines données afin d'éviter les conflits lors de la fusion

source central

nbParamsautorises=1
cheminScript=${CHEMIN_RACINE}
script_a_lancer=${SCRIPT_A_LANCER}
passwordRoot=${PASSWORD_ROOT}

sql=$1
cheminSQL=${CHEMIN_SQL}

aide(){
    echo -e "\n\n Ce script prend un paramètre : Le nom du fichier.sql dont le contenu sera appliqué à la base destination. Ce fichier sql doit être situé dans le répertoire ${cheminSQL}\n\n"
}

requetes(){
	# Définition d'un fichier temporaire
	fichierCommande="commande"
	cd ${cheminScript}
	# On stocke la commande à exécuter dans ce fichier temporaire
	echo "mysql -uroot -p${passwordRoot} < ${cheminSQL}\"/\"${sql}"> ${fichierCommande}
	# On lance le script en lui passant la commande que l'on vient de stocker
	./${script_a_lancer} < ${fichierCommande}
	if [ "$?" = "1" ]; then
		echo -e "Impossible d'exécuter le script. Vérifier les chemin d'accès\n"
		exit 1
	fi
	# On supprime le fichier temporaire
	rm ${fichierCommande}
	echo -e "SUCCES ! Le fichier ${sql} a été importé dans la base destination"
}

if [ "$1" == "-h" ]
then
	echo -e "\nAide"
	aide
	exit 0
elif [ ${nbParamsautorises} -ne $# ]
then
	echo -e "\n\n	Il faut passer "${nbParamsautorises}" parametre(s)"
	echo -e "Exemple :	"$0" test.sql\n\n"
	exit 0
else
	requetes
	exit 0
fi

